(defun color-theme-nox ()
  "Nice 256 color layout for transparent backgrounds"
  (interactive)
  (color-theme-install
   '(color-theme-nox
     (
      (background-color . nil)
      (border-color . "black")
      (background-mode . nil)
      (cursor-color . "Plum1")
      (foreground-color . "#8bcd8b")
      (mouse-color . "yellow1")
      (top-toolbar-shadow-color . "#e5e5e0e0e1e1")
      )
     (default ((t (nil))))
     (blue ((t (:foreground "#00cdff"))))
     (bold ((t (:bold t))))
     (bold-italic ((t (nil))))
     (border-glyph ((t (nil))))
     (fringe ((t (:background "#5c5c5c" .color "yellow"))))
     (font-lock-builtin-face ((t (:foreground "#8b8b8b"))))
     (highline-face ((t (:foreground "#8bcd8b" :background "#4d4d4d"))))
     (font-lock-comment-face ((t (:bold t :foreground "#737373" :height 0.8))))
     (font-lock-comment-delimiter-face ((t (:bold t :foreground "#737373" :heigh 0.8))))
     (font-lock-constant-face ((t (:bold t :foreground "#8bffcd" ))))
     (font-lock-doc-string-face ((t (:foreground "#00C000"))))
     (font-lock-doc-face ((t (:foreground "SkyBlue1" :background "RoyalBlue4"))))
     (font-lock-function-name-face ((t (:bold nil :foreground "#cdff8b" :height 1.2))))
     (font-lock-keyword-face ((t (:bold t :foreground "#ffcd00" :height 1.1))))
     (font-lock-other-emphasized-face ((t (:bold t :foreground "gold1"))))
     (font-lock-other-type-face ((t (:bold nil :foreground "gold1"))))
     (font-lock-preprocessor-face ((t (:foreground "plum"))))
     (font-lock-reference-face ((t (:bold t :foreground "orangered"))))
     (font-lock-string-face ((t (:foreground "plum" ))))
     (font-lock-type-face ((t (:bold t :foreground "ivory2" :height 1.1))))
     (font-lock-variable-name-face ((t (:foreground "#00ff00"))))
     (font-lock-warning-face ((t (:foreground "tomato"))))
     (flyspell-incorrect ((t (:foreground "#ff8b00"))))
     (flyspell-duplicate ((t (:foreground "#cdcd00"))))
     (green ((t (:foreground "green"))))
     (gui-button-face ((t (:background "grey75" :foreground "black"))))
     (gui-element ((t (:size "nil" :background "#e7e3d6" :foreground" #000000"))))
     (highlight ((t (:background "firebrick4" :foreground "yellow1"))))
     (isearch ((t (:bold t :background "pale turquoise" :foreground "blue"))))
     (italic ((t (nil))))
     (lazy-highlight-face ((t (:bold t :foreground "dark magenta"))))
     (left-margin ((t (nil))))
     (list-mode-item-selected ((t (:bold t :background "gray68" :foreground "yellow"))))
     ;;:overline "CadetBlue" :underline "turquoise4"
     (modeline ((t (:background "#2e2e2e" :foreground "#cdcd8b" :height 0.8))))
     (rcirc-timestamp ((t (:foreground "#5c5c5c"))))
     (rcirc-my-nick ((t (:foreground "#cdff8b"))))
     (rcirc-server ((t (:foreground "#737373"))))
     (rcirc-other-nick ((t (:foreground "#00ff8b"))))
     (rcirc-bright-nick ((t (:foreground "#8bff00-"))))
     (rcirc-prompt ((t (:foreground "cyan"))))
     (minibuffer-prompt ((t (:foreground "#fff" :background "brightred" :bold t))))
     (mode-line-inactive ((t (:italic t :background "#2e2e2e" :foreground "#5c5c5c" :box (:line-width -1 :color "SeaGreen") :slant oblique :weight light :height 0.8))))
     (modeline-buffer-id ((t (:background "#4d4d4d" :foreground "#8bff00k"))))
     (modeline-mousable ((t (:background "red" :foreground "darkblue"))))
     (modeline-mousable-minor-mode ((t (:background "sienna" :foreground "darkblue"))))
     (paren-blink-off ((t (:foreground "DodgerBlue4"))))
     (paren-match ((t (:background "red" :foreground "yellow"))))
     (paren-mismatch ((t (:background "DeepPink"))))
     (pointer ((t (:background "white"))))
     (primary-selection ((t (:bold t :background "medium sea green"))))
     (red ((t (:foreground "red"))))
     (diff-file-header ((t (:foreground "#8b8b8b" :bold t))))
     (diff-header ((t (:foreground "#8b8b8b"))))
     (diff-removed ((t (:foreground "#008b8b"))))
     (diff-added ((t (:foreground "#8bff8b"))))
     (diff-indicator-added ((t (:foreground "#8bff8b"))))
     (region ((t (:background "MediumSeaGreen" :foreground "yellow"))))
     (right-margin ((t (nil))))
     (secondary-selection ((t (:background "gray91" :foreground "sienna3"))))
     ;; (show-paren-match-face ((t (:background "cyan3" :foreground "blue"))))
     (howm-reminder-done-face ((t (:background "#00cd00" :foreground "black"))))
     
     (show-paren-mismatch-face ((t (:background "red" :foreground "blue"))))
     (show-trailing-whitespace ((t (:background "red" :foreground "blue"))))
     (text-cursor ((t (:background "tan" :foreground "DodgerBlue4"))))
     (toolbar ((t (:background "#e7e3d6" :foreground "#000000"))))
     (underline ((t (:underline t))))
     (vertical-divider ((t (:background "red" :foreground "yellow"))))
     (widget-button-face ((t (:bold t))))
     (widget-button-pressed-face ((t (:foreground "red"))))
     (widget-documentation-face ((t (:foreground "dark green"))))
     (widget-field-face ((t (:background "gray85"))))
     (widget-inactive-face ((t (:foreground "dim gray"))))
     (widget-single-line-field-face ((t (:background "gray85"))))
     (yellow ((t (:foreground "yellow"))))
     (circe-originator-face ((t (:foreground "OliveDrab2"))))
     (circe-my-message-face ((t (:foreground "SpringGreen3"))))
     (circe-highlight-nick-face ((t (:foreground "orchid2"))))
     (circe-server-face ((t (:foreground "thistle4"))))
     (circe-prompt-face ((t (:foreground "yellow1" :height 1.0))))
     (lui-button-face ((t (:foreground "yellow1"))))
     (lui-time-stamp-face ((t (:foreground "CadetBlue"))))
     (dired-warning ((t (:foreground "Orange"))))
     (dired-directory ((t (:foreground "LightBlue"))))
     (dired-filename ((t (:foreground "PaleGreen"))))
     
     (comint-highlight-prompt ((t (:foreground "grey10"))))
     (compilation-error ((t (:foreground "grey10"))))
     (compilation-line-number  ((t (:foreground "grey10"))))
     (eshell-ls-archive-face ((t (:bold t :foreground "IndianRed"))))
     (eshell-ls-backup-face ((t (:foreground "Grey"))))
     (eshell-ls-clutter-face ((t (:foreground "DimGray"))))
     (eshell-ls-directory-face ((t (:bold t :foreground "MediumSlateBlue"))))
     (eshell-ls-executable-face ((t (:foreground "Coral"))))
     (eshell-ls-missing-face ((t (:foreground "black"))))
     (eshell-ls-picture-face ((t (:foreground "Violet")))) ; non-standard face
     (eshell-ls-product-face ((t (:foreground "LightSalmon"))))
     (eshell-ls-readonly-face ((t (:foreground "Aquamarine"))))
     (eshell-ls-special-face ((t (:foreground "Gold"))))
     (eshell-ls-symlink-face ((t (:foreground "White"))))
     (eshell-ls-text-face ((t (:foreground "medium aquamarine")))) ; non-standard face
     (eshell-ls-todo-face ((t (:bold t :foreground "aquamarine")))) ; non-standard face
     (eshell-ls-unreadable-face ((t (:foreground "DimGray"))))
     (eshell-prompt-face ((t (:foreground "powder blue"))))
     (emms-playlist-selected-face ((t (:foreground "#8bcd8b" :underline t))))
     (emms-playlist-track-face ((t (:foreground "#8b8b8b"))))
     (emms-browser-album-face ((t (:foreground "#ff8b8b"))))
     (zmacs-region ((t (:background "white" :foreground "midnightblue")))))))

