(defun color-theme-dd ()
  "Color theme based on the Inkpot theme. Ported and tweaked by Per Vognsen."
  (interactive)
  (color-theme-install
   '(color-theme-dd
     (
      (foreground-color . "#cdcdb4")
      (background-color . "#1e1e27")
      (cursor-color . "#b86800")
      (background-mode . dark)
      (mouse-color . "#7cfc00"))
     (region ((t (:background "#0a0a0a"))))
     (show-paren-match-face ((t (:background "#606060"))))
     (fringe ((t (:background "#18181d"))))
     (isearch ((t (:bold t :foreground "#303030" :background "#cd8b60"))))
     (minibuffer-prompt ((t (:bold t :weight bold :foreground "red" :background "grey90"))))
     (modeline ((t (:bold t :foreground "#ac9c9c" :background "#3e3e5e" :height 0.7))))
     (mode-line-inactive ((t (:italic t :bold nil :foreground "#3e3e47" :background "#2c2c35" :box (:line-width -1 :color "#3e3e5e") :slant oblique :height 0.7))))
     (modeline-buffer-id ((t (:bold nil :foreground "#1e1e27" :background "#3e3e5e"))))
     (font-lock-builtin-face ((t (:foreground "#c080d0"))))
     (font-lock-comment-face ((t (:foreground "#5c5c5c" :background "#212121"))))
     (bm-face ((t (:foreground "#ff8c00" :background "#483d8b"))))
     (font-lock-comment-delimiter-face ((t (:foreground "#8b6969"))))
     (font-lock-constant-face ((t (:foreground "#ff4500"))))
     (font-lock-doc-string-face ((t (:foreground "#cd8b00"))))
     (font-lock-function-name-face ((t (:foreground "#cd950c"))))
     (font-lock-keyword-face ((t (:bold t :foreground "#c080d0"))))
     (font-lock-preprocessor-face ((t (:foreground "309090"))))
     (font-lock-reference-face ((t (:bold t :foreground "#808bed"))))
     (font-lock-string-face ((t (:foreground "#ffcd8b" :background "#404040"))))
     (font-lock-type-face ((t (:foreground "#ff8bff"))))
     (font-lock-variable-name-face ((t (:foreground "#ADFF31"))))
     (font-lock-warning-face ((t (:foreground "#cd9b9b" :background "#8b2500"))))

     (ruby-complexity-complexity-low ((t (:foreground "#7f7f7f"))))
     (ruby-complexity-complexity-normal ((t (:foreground "#d4d4d4"))))
     (ruby-complexity-complexity-high ((t (:foreground "#7f007f"))))
     (show-paren-match-face ((t (:foreground "green" :background nil))))
     (show-paren-mismatch-face ((t (:foreground "red" :background nil))))
     (js2-keyword-face ((t (:bold t :foreground "#c080d0"))))
     (js2-function-name-face ((t (:foreground "#cd950c"))))
     (js2-string-face ((t (:foreground "#ffcd8b" :background "#404040"))))
     (js2-builtin-face  ((t (:foreground "#ADFF31"))))
     (js2-variable-name-face ((t (:foreground "#ADFF31"))))

     (textile-link-face ((t (:foreground "#4d88cf"))))
     (textile-ul-bullet-face ((t (:foreground "#00ff00"))))

     (howm-menu-key-face ((t (:foreground "orange"))))
     (howm-menu-list-face ((t (:foreground "white"))))
     (howm-mode-keyword-face ((t (:background "dodgerblue4" :foreground "cyan" :underline nil :slant normal))))
     (howm-mode-ref-face ((t (:italic t :foreground "greenyellow" :slant italic))))
     (howm-mode-title-face ((t (:bold t :background "dodgerblue4" :foreground "cyan" :box (:line-width 8 :color "dodgerblue4") :underline nil :weight bold))))
     (howm-mode-wiki-face ((t (:background "dodgerblue4" :foreground "cyan" :underline nil))))
     (howm-reminder-deadline-face ((t (:background "red" :foreground "yellow" :underline nil :weight normal))))
     (howm-reminder-defer-face ((t (:background "purple4" :foreground "magenta" :weight normal))))
     (howm-reminder-done-face ((t (:foreground "gray"))))
     (howm-reminder-normal-face ((t (:background "darkgreen" :foreground "yellow" :underline nil :weight normal))))
     (howm-reminder-schedule-face ((t (:background "darkorange2" :foreground "yellow" :slant normal :weight normal))))
     (howm-reminder-separator-face ((t (:foreground "black"))))
     (howm-reminder-today-face ((t (:bold t :box nil :weight bold))))
     (howm-reminder-todo-face ((t (:background "dodgerblue4" :foreground "cyan" :underline nil :weight normal))))
     (howm-reminder-tomorrow-face ((t (:background "pink" :foreground "black"))))
     (howm-view-empty-face ((t (nil))))
     (howm-view-hilit-face ((t (:foreground "red"))))
     (howm-view-name-face ((t (nil))))
     (rcirc-server ((t (:foreground "#333333" :height 0.7))))
     (rcirc-text ((t (:foreground "#2e2e42" :height 0.7))))
     (rcirc-timestamp ((t (:foreground "#6c7b8b" :height 0.7))))
     (rcirc-prompt ((t (:foreground "#545466"))))
     (rcirc-nick-in-message-full-line ((t (:foreground "#cd5b45"))))
     (rcirc-dim-nick ((t (:foreground "#474764"))))
     (rcirc-bright-nick ((t (:foreground "#ff7f50"))))
     (rcirc-other-nick ((t (:foreground "#ADFF31"))))
     (rcirc-server-prefix ((t (:foreground "#474764"))))
     (rcirc-my-nick ((t (:foreground "#ff69b4"))))     
     (circe-originator-face ((t (:foreground "#8b7d6b"))))
     (circe-my-message-face ((t (:foreground "#eec900"))))
     (circe-highlight-nick-face ((t (:foreground "#8b7d6b"))))
     (circe-server-face ((t (:foreground "#454545"))))
     (circe-prompt-face ((t (:foreground "#eec900" :height 1.0))))
     (lui-button-face ((t (:foreground "yellow1"))))
     (lui-time-stamp-face ((t (:foreground "#8b8878"))))
     (flyspell-incorrect ((t (:foreground "#ba946a" :underline "#a95329"))))
     (flyspell-duplicate ((t (:foreground "#806a52" :underline "#a95329"))))
     (mew-face-header-key ((t (:foreground "#6d300f"))))
     (mew-face-header-important ((t (:bold t :foreground "#8f7e5c"))))
     (mew-face-header-to ((t (:foreground "#8a89a4"))))
     (mew-face-header-from ((t (:foreground "#bfbed4" :bold t))))
     (mew-face-header-marginal ((t (:foreground "#2e2e42"))))
     (mew-face-header-date ((t (:foreground "#5c5b77"))))
     (mew-face-header-private ((t (:foreground "red4"))))
     (mew-face-header-subject ((t (:bold t :foreground "#7fa29f" :height 1.3))))
     (mew-face-body-url ((t (:foreground "#bf792d"))))
     (mew-face-body-cite1  ((t (:foreground "#46464b"))))
     (dired-directory ((t (:bold t :foreground "khaki" :weight bold))))
     (dired-face-boring ((t (:foreground "Gray65"))))
     (dired-face-directory ((t (:bold t :foreground "sky blue" :weight bold))))
     (dired-face-executable ((t (:foreground "green yellow"))))
     (dired-face-flagged ((t (:foreground "tomato"))))
     (dired-face-header ((t (:background "grey75" :foreground "gray30"))))
     (dired-face-marked ((t (:italic t :foreground "slate gray" :slant italic))))
     (dired-face-permissions ((t (:foreground "aquamarine"))))
     (dired-face-setuid ((t (:foreground "gray85"))))
     (dired-face-socket ((t (:foreground "gray85"))))
     (dired-face-symlink ((t (:foreground "cyan"))))
     (dired-flagged ((t (:foreground "red"))))
     (dired-header ((t (:bold t :weight bold :height 1.44 :family "helv"))))
     (dired-ignored ((t (:foreground "gray50"))))
     (dired-mark ((t (:foreground "yellow" :background "red" :bold t :weight bold))))
     (dired-marked ((t (:italic t :foreground "slate gray" :slant italic))))
     (dired-symlink ((t (:foreground "IndianRed1"))))
     (dired-warning ((t (nil))))
     (comint-highlight-prompt ((t (:foreground "#7F8F98" :bold t))))
)))

(provide 'color-theme-dd)
